# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 739af989f24116f96f5a61583035c6999cec920b3a20614b4e3c2424d47cbf0a7851cfd0a7c6a3b26eaa0e2f35e2c19d11c9d6a3083f3f4d6cc7af30a8f8a904

test:
  secret_key_base: 40f03882d8116f3489e1e0d87e2a51124adb6f548c2ab0d2bcd77eb5f42d800b4f0242a2297848e012c819d684429080bd930e544e410e67529e8ebca1e862e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
